/*import{Cliente}from './clientes';
export const CLIENTES:Cliente[]=[
    {
      id:1,
      nombre:'Johann',
      apellido:'Arizaga',
      createate:'2003-1-16',
      email:'johannarizaga010@gmail.com'
    },
    {
      id:2,
      nombre:'Johann2',
      apellido:'Arizaga',
      createate:'2003-1-16',
      email:'johannarizaga010@gmail.com'
    },
    {
      id:3,
      nombre:'Johann3',
      apellido:'Arizaga',
      createate:'2003-1-16',
      email:'johannarizaga010@gmail.com'
    },
    {
      id:4,
      nombre:'Johann3',
      apellido:'Arizaga',
      createate:'2003-1-16',
      email:'johannarizaga010@gmail.com'
    },
    {
      id:5,
      nombre:'Andy',
      apellido:'Arizaga',
      createate:'2011-1-16',
      email:'andyarizaga010@gmail.com'
    },
    
    ];*/